import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import * as Realm from "realm-web";

export default function Home() {
  const [movies, setMovies] = useState([]);

  useEffect(
    () => {
      (async function getMovieData() {
        const REALM_APP_ID = "movies-vyvch";
        const app = new Realm.App({ id: REALM_APP_ID });
        const credentials = Realm.Credentials.anonymous();

        try {
          const user = await app.logIn(credentials);
          const allMovies = await user.functions.getAllMovies();

          setMovies(allMovies);

          console.log(allMovies);
        } catch (error) {
          console.error(error);
        }

        // const mongo = app.currentUser?.mongoClient('WK-Free-Cluster');
        // const collection = mongo?.db('sample_mflix').collection('movies');

        // const allMovies = await collection?.find();
        // console.log(allMovies);
  })();
},
    []
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {movies ? (
          movies.map((movie) => {
            return (
              <>
                <h3 key={movie._id}>{movie.title}</h3>
                <p key={`${movie._id}pp`}>{movie.plot}</p>
              </>
            );
          })
        ) : (
          <p>No Movie Found</p>
        )}
      </main>
    </>
  );
}
